spring:
  application:
    name: serve-amq-consumer
  zipkin:
    # base-url: @zipkin.url@  #若在同一个注册中心的话可以启用自动发现，省略base-url
    locator:
      discovery:
        enabled: true #自动发现
  boot:
    admin:
      client:
#        url: @admin.url@
        instance:
          service-base-url: @admin.url@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.105.161.199:3306/mydb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: @db.user@
    password: @db.pwd@
  rabbitmq:
    port: 5672
    host: @rabbitmq.host@
    username: @rabbitmq.user@
    password: @rabbitmq.pwd@
  cloud:
    stream:
      bindings:
        input_channel:
          destination: exchange-3
          group: queue-3              # group相当于RabbitMQ中Queue的名称
          consumer:
            ##默认监听数
            concurrency: 1
      rabbit:
        bindings:
          input_channel:
            consumer:
              ##针对消费端channel进行设置，是否支持requeue，重回队列
              requeue-rejected: false
              ##是否支持签收，签收模式：手工签收
              acknowledge-mode: MANUAL
              ##服务重连
              recovery-interval: 3000
              ##是否持久化订阅
              durable-subscription: true
              ## 最大监听数
              max-concurrency: 5

server:
  port: @serve.mq.port@

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: @eureka.url@

logging:
  level:
    root: info
    com.lzlm.cn: debug

