spring:
  application:
    name: serve-gateway
  boot:
    admin:
      client:
        url: @admin.url@
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: host_route
        uri: http://www.baidu.com #lb://SERVE-AUTH
        predicates:
        - Path=/lzlm
#        filters:
#        - StripPrefix=1
server:
  port: @serve.gateway.port@
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: @eureka.url@
loggin:
  level:
    root: info
    com.lzlm.cn: debug

